### ISSUE TITLE
MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by gitscosh** [robb-j/nova-yaml-language-server#27]
Ok, so I gave up on NVM and just installed node the regular way. I also checked the box in Nova preferences to "Automatically request environment from login shell" which in my case is zsh. I have opened terminal which runs zsh by default and successfully executed which node (/usr/local/bin/node) and which npm (/usr/local/bin/npm). When I install the YAML extension in Nova, I get the following error in the Extension Console:

Yaml Language Server[2:17:23.115000] node:internal/modules/cjs/loader:942

Yaml Language Server[2:17:23.115000]   throw err;

Yaml Language Server[2:17:23.115000]   ^

Yaml Language Server[2:17:23.115000] 

Yaml Language Server[2:17:23.115000] Error: Cannot find module '/Users/username/Library/Application Support/Nova/Extensions/robb-j.yaml/node_modules/yaml-language-server/out/server/src/server.js'

Yaml Language Server[2:17:23.115000]     at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)

Yaml Language Server[2:17:23.115000]     at Module._load (node:internal/modules/cjs/loader:780:27)

Yaml Language Server[2:17:23.115000]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

Yaml Language Server[2:17:23.115000]     at node:internal/main/run_main_module:17:47 {

Yaml Language Server[2:17:23.115000]   code: 'MODULE_NOT_FOUND',

Yaml Language Server[2:17:23.115000]   requireStack: []

Yaml Language Server[2:17:23.115000] }

Yaml Language Server[2:17:23.115000] 

Yaml Language Server[2:17:23.115000] Node.js v18.3.0

Any ideas?

**Comment by gitscosh** [comment]
In case anyone else has this issue, it turned out there were two folders for this extension in /Users/username/Library/ApplicationSupport/Nova/Extensions for some reason, and I think it was causing a conflict. After uninstalling the extension via Nova, there was one folder remaining for robb-j.yaml so I rm -rf'ed it and then reinstalled the extension and it is now working.

What a headache. Not your fault! Just don't know if it's a Mac thing or a Nova thing but geez Louise.  Thanks for your help!

**Comment by robb-j** [comment]
That's quite strange, I'm not sure how that happened I've added an extra check to the during the "install" part of the setup which should show an error notification if this happens again
