### ISSUE TITLE
Custom tags support

### ISSUE THREAD

**Issue by SdeGeata** [robb-j/nova-yaml-language-server#3]
Hello!

   I just installed your Nova extension to verify YAML files. It apparently has an issue with `!secret` tags.

![Screen Shot 2021-03-13 at 11 05 53 PM](https://user-images.githubusercontent.com/5808871/111056991-eab6d480-8451-11eb-9c70-f9bea26acb23.png)

  Just wanted to bring it to your attention.

**Comment by robb-j** [comment]
Hey, I've started a PR #5 which adds support for custom tags and a few other things. Tags aren't a feature I've used yet, could you let me know if the updated readme makes sense? 

([updated readme link](https://github.com/robb-j/nova-yaml-language-server/tree/add-configuration/yaml.novaextension))

Also there's the option for globally set custom tags or just per-workspace. I've put in support for both but it doesn't merge them together so there may be duplication. I'd be interested to know your thoughts on per-project vs global.

**Comment by SdeGeata** [comment]
Seems to make sense, i’ll have to give it a try.

**Comment by robb-j** [comment]
I've released 1.1.0 of the extension but it doesn't seem to be sending the "custom tags" property to the yaml server properly on first start up. It does apply it when you edit the preference field, but then won't again when you restart Nova.

I'll look further into it soon.

**Comment by robb-j** [comment]
Is this working as expected now? If so I'll close this issue
